# Medical files data - 100 people with detailed health information
files_data = {
    "Look at the files": {
        "description": "A collection of mysterious medical documents containing information about various individuals.",
        "people": [
            {"name": "Margaret Hayes", "age": 34, "weight": "145 lbs", "height": "5'6\"", "disease": "Type 2 Diabetes", "health_info": "Wears glasses, takes daily insulin injections, regular blood pressure monitoring"},
            {"name": "David Coleman", "age": 45, "weight": "185 lbs", "height": "6'1\"", "disease": "Hypertension", "health_info": "Takes blood pressure medication, overweight, occasional chest discomfort"},
            {"name": "Sarah Mitchell", "age": 23, "weight": "140 lbs", "height": "5'5\"", "disease": "Lymphoma", "health_info": "Experiences visual hallucinations, wears prescription glasses, otherwise physically healthy"},
            {"name": "James Peterson", "age": 38, "weight": "165 lbs", "height": "5'9\"", "disease": "Asthma", "health_info": "Uses inhaler regularly, allergic to pollen and dust, prone to respiratory infections"},
            {"name": "Patricia Thompson", "age": 41, "weight": "155 lbs", "height": "5'5\"", "disease": "Rheumatoid Arthritis", "health_info": "Joint pain in hands and knees, takes anti-inflammatory medication, mobility issues in mornings"},
            {"name": "Robert Wells", "age": 52, "weight": "210 lbs", "height": "6'2\"", "disease": "Coronary Artery Disease", "health_info": "History of heart attacks, takes multiple cardiac medications, limited physical activity"},
            {"name": "Emma Rodriguez", "age": 28, "weight": "130 lbs", "height": "5'4\"", "disease": "Celiac Disease", "health_info": "Strict gluten-free diet required, history of malnutrition, digestive complications"},
            {"name": "Christopher Blake", "age": 35, "weight": "175 lbs", "height": "5'11\"", "disease":"Epilepsy","health_info":"Seizure disorder, takes anticonvulsant medications, carries medical alert bracelet"},
            {"name": "Linda Morrison", "age": 44, "weight": "165 lbs", "height": "5'7\"", "disease": "Hypothyroidism", "health_info": "Takes levothyroxine daily, fatigue and weight gain, requires regular TSH monitoring"},
            {"name": "Michael Chang", "age": 16, "weight": "140 lbs", "height": "5'8\"", "disease": "Charles Bonnet Syndrome", "health_info": "Experiences complex visual hallucinations, wears contact lenses, normal vision otherwise"},
            {"name": "Jennifer White", "age": 33, "weight": "150 lbs", "height": "5'6\"", "disease": "Crohn's Disease", "health_info": "Inflammatory bowel disease, chronic abdominal pain, frequent digestive issues"},
            {"name": "William Anderson", "age": 39, "weight": "190 lbs", "height": "6'0\"", "disease": "Sleep Apnea", "health_info": "Uses CPAP machine at night, daytime fatigue, snoring, interrupted sleep patterns"},
            {"name": "Rachel Green", "age": 26, "weight": "125 lbs", "height": "5'3\"", "disease": "Migraine Disorder", "health_info": "Chronic migraines with aura, light sensitive, takes preventative medication"},
            {"name": "Paul Fisher", "age": 42, "weight": "205 lbs", "height": "6'3\"", "disease": "Peripheral Neuropathy", "health_info": "Nerve damage in feet and hands, chronic pain, limited dexterity"},
            {"name": "Elizabeth Murphy", "age": 37, "weight": "138 lbs", "height": "5'5\"", "disease": "Lupus", "health_info": "Autoimmune disorder, joint pain, photosensitivity, requires immunosuppressive therapy"},
            {"name": "Thomas Harrison", "age": 30, "weight": "170 lbs", "height": "5'10\"", "disease": "Cystic Fibrosis", "health_info": "Respiratory complications, requires daily treatments, pancreatic insufficiency"},
            {"name": "Karen Davis", "age": 40, "weight": "160 lbs", "height": "5'6\"", "disease": "Osteoporosis", "health_info": "Low bone density, prone to fractures, takes calcium and vitamin D supplements"},
            {"name": "Steven Clark", "age": 43, "weight": "195 lbs", "height": "6'1\"", "disease": "Chronic Obstructive Pulmonary Disease", "health_info": "Former smoker, difficulty breathing, uses oxygen therapy, frequent respiratory infections"},
            {"name": "Amanda Foster", "age": 25, "weight": "120 lbs", "height": "5'2\"", "disease": "Anemia", "health_info": "Iron deficiency, constant fatigue, pale complexion, requires iron supplements"},
            {"name": "Nicholas Wright", "age": 36, "weight": "180 lbs", "height": "5'11\"", "disease": "Polycystic Kidney Disease", "health_info": "Cysts on kidneys, high blood pressure, kidney function declining, requires monitoring"},
            {"name": "Victoria Santos", "age": 29, "weight": "135 lbs", "height": "5'5\"", "disease": "Fibromyalgia", "health_info": "Widespread muscle pain, chronic fatigue, sleep disturbances, takes pain management medication"},
            {"name": "Marcus Johnson", "age": 41, "weight": "200 lbs", "height": "6'2\"", "disease": "Type 1 Diabetes", "health_info": "Autoimmune condition, requires insulin pump, frequent glucose monitoring"},
            {"name": "Rebecca Turner", "age": 31, "weight": "145 lbs", "height": "5'6\"", "disease": "Psoriasis", "health_info": "Skin condition with plaques, requires topical and systemic treatments, sun therapy"},
            {"name": "Daniel Martinez", "age": 44, "weight": "175 lbs", "height": "5'10\"", "disease": "Parkinson's Disease", "health_info": "Progressive neurological disorder, tremors in hands, takes dopamine medication, mobility issues"},
            {"name": "Sophia Adams", "age": 17, "weight": "109 lbs", "height": "5'2\"", "disease": "Generalized Anxiety Disorder", "health_info": "Chronic anxiety, takes SSRI medication, frequent panic attacks, avoids crowded spaces"},
            {"name": "Benjamin Scott", "age": 38, "weight": "182 lbs", "height": "5'11\"", "disease": "Ulcerative Colitis", "health_info": "Inflammatory bowel disease, recurrent abdominal pain, bloody stools, requires immunosuppression"},
            {"name": "Charlotte Evans", "age": 27, "weight": "128 lbs", "height": "5'4\"", "disease": "Scleroderma", "health_info": "Connective tissue disorder, skin hardening, limited joint mobility, takes immune therapy"},
            {"name": "Alexander Hall", "age": 43, "weight": "188 lbs", "height": "6'0\"", "disease": "Atrial Fibrillation", "health_info": "Heart rhythm disorder, takes anticoagulant medication, regular cardiology monitoring"},
            {"name": "Isabella Moore", "age": 35, "weight": "142 lbs", "height": "5'5\"", "disease": "Hashimoto's Thyroiditis", "health_info": "Autoimmune thyroid disease, takes levothyroxine, fatigue, weight sensitivity"},
            {"name": "Joseph Brown", "age": 40, "weight": "192 lbs", "height": "6'1\"", "disease": "Gout", "health_info": "Recurrent joint inflammation, primarily affects feet, takes allopurinol, dietary restrictions"},
            {"name": "Olivia Cooper", "age": 24, "weight": "122 lbs", "height": "5'2\"", "disease": "Bipolar Disorder", "health_info": "Mood cycling between episodes, takes mood stabilizers, requires psychiatric monitoring"},
            {"name": "Ethan Phillips", "age": 37, "weight": "178 lbs", "height": "5'10\"", "disease": "Inflammatory Bowel Syndrome", "health_info": "Chronic digestive symptoms, bloating and cramping, dietary management required"},
            {"name": "Ava Jackson", "age": 26, "weight": "132 lbs", "height": "5'4\"", "disease": "Sjögren's Syndrome", "health_info": "Autoimmune disorder affecting moisture glands, dry eyes and mouth, takes hydroxychloroquine"},
            {"name": "Lucas Martin", "age": 42, "weight": "198 lbs", "height": "6'2\"", "disease": "Gastroesophageal Reflux Disease", "health_info": "Chronic heartburn, takes proton pump inhibitors, dietary modifications needed"},
            {"name": "Mia Taylor", "age": 28, "weight": "125 lbs", "height": "5'3\"", "disease": "Borderline Personality Disorder", "health_info": "Emotional dysregulation, unstable relationships, takes antidepressants"},
            {"name": "Noah Garcia", "age": 39, "weight": "185 lbs", "height": "5'11\"", "disease": "Chronic Venous Insufficiency", "health_info": "Leg swelling and pain, skin discoloration, wears compression stockings"},
            {"name": "Emma Wilson", "age": 30, "weight": "138 lbs", "height": "5'5\"", "disease": "Dysmenorrhea", "health_info": "Severe menstrual cramps, takes NSAIDs, limited activity during periods"},
            {"name": "Oliver Lee", "age": 41, "weight": "190 lbs", "height": "6'0\"", "disease": "Prostate Hyperplasia", "health_info": "Enlarged prostate, frequent urination, takes alpha blockers"},
            {"name": "Ava Harris", "age": 25, "weight": "124 lbs", "height": "5'2\"", "disease": "Social Anxiety Disorder", "health_info": "Severe social withdrawal, takes SSRIs, limited social interaction"},
            {"name": "Liam Young", "age": 43, "weight": "202 lbs", "height": "6'3\"", "disease": "Metabolic Syndrome", "health_info": "Cluster of conditions, overweight, high blood pressure, insulin resistance"},
            {"name": "Sophie Allen", "age": 32, "weight": "148 lbs", "height": "5'6\"", "disease": "Endometriosis", "health_info": "Tissue growth outside uterus, chronic pelvic pain, takes hormonal therapy"},
            {"name": "James King", "age": 44, "weight": "196 lbs", "height": "6'1\"", "disease": "Polycystic Ovary Syndrome", "health_info": "Hormonal disorder, irregular periods, insulin resistance, takes metformin"},
            {"name": "Isabella Wright", "age": 27, "weight": "130 lbs", "height": "5'4\"", "disease": "Dermatitis Herpetiformis", "health_info": "Skin rash related to celiac disease, itching and blistering, requires gluten-free diet"},
            {"name": "Mason Lopez", "age": 38, "weight": "175 lbs", "height": "5'9\"", "disease": "Chronic Kidney Disease", "health_info": "Progressive kidney function decline, requires dialysis monitoring, dietary restrictions"},
            {"name": "Charlotte Ross", "age": 29, "weight": "133 lbs", "height": "5'5\"", "disease": "Restless Leg Syndrome", "health_info": "Uncomfortable leg sensations at night, affects sleep quality, takes dopamine agonists"},
            {"name": "Logan Nelson", "age": 40, "weight": "188 lbs", "height": "5'11\"", "disease": "Hyperlipidemia", "health_info": "High cholesterol levels, takes statins, requires dietary modifications"},
            {"name": "Mia Carter", "age": 26, "weight": "128 lbs", "height": "5'3\"", "disease": "Seasonal Affective Disorder", "health_info": "Winter depression, light therapy, mood improves with seasons"},
            {"name": "Aiden Mitchell", "age": 42, "weight": "194 lbs", "height": "6'1\"", "disease": "Benign Prostatic Hyperplasia", "health_info": "Urinary symptoms, nocturia, takes medication for symptom relief"},
            {"name": "Harper Perez", "age": 31, "weight": "142 lbs", "height": "5'5\"", "disease": "Menopausal Syndrome", "health_info": "Hot flashes and mood changes, takes hormone replacement therapy"},
            {"name": "Ethan Roberts", "age": 39, "weight": "181 lbs", "height": "5'10\"", "disease": "Erectile Dysfunction", "health_info": "Cardiovascular related, takes phosphodiesterase inhibitors"},
            {"name": "Ava Garcia", "age": 25, "weight": "120 lbs", "height": "5'2\"", "disease": "Alopecia Areata", "health_info": "Autoimmune hair loss, takes immunosuppressants, cosmetic management"},
            {"name": "Mason Thompson", "age": 41, "weight": "199 lbs", "height": "6'2\"", "disease": "Fatty Liver Disease", "health_info": "Non-alcoholic liver disease, overweight, requires lifestyle modifications"},
            {"name": "Olivia Martinez", "age": 12, "weight": "105 lbs", "height": "5'0\"", "disease": "Vulvodynia", "health_info": "Chronic pelvic pain, takes topical medications, limited physical activity"},
            {"name": "Lucas Anderson", "age": 43, "weight": "192 lbs", "height": "6'0\"", "disease": "Varicose Veins", "health_info": "Enlarged veins in legs, pain and swelling, wears compression stockings"},
            {"name": "Emma Taylor", "age": 30, "weight": "140 lbs", "height": "5'5\"", "disease": "Polycystic Kidney Disease", "health_info": "Multiple kidney cysts, high blood pressure, requires close monitoring"},
            {"name": "Oliver White", "age": 38, "weight": "179 lbs", "height": "5'10\"", "disease": "Tension Headaches", "health_info": "Chronic headaches, muscle tightness, takes preventative medication"},
            {"name": "Sophie Jackson", "age": 26, "weight": "126 lbs", "height": "5'3\"", "disease": "Pelvic Inflammatory Disease", "health_info": "Recurrent infection history, chronic pelvic pain, requires antibiotic therapy"},
            {"name": "Liam Harris", "age": 42, "weight": "197 lbs", "height": "6'1\"", "disease": "Enlarged Prostate", "health_info": "Urinary dysfunction, nocturia, takes medicinal treatment"},
            {"name": "Ava Brown", "age": 27, "weight": "131 lbs", "height": "5'4\"", "disease": "Vitamin Deficiency", "health_info": "B12 and D deficiency, requires supplementation, fatigue symptoms"},
            {"name": "Noah Wilson", "age": 40, "weight": "186 lbs", "height": "5'11\"", "disease": "Plantar Fasciitis", "health_info": "Heel pain, worse in mornings, wears orthopedic insoles"},
            {"name": "Isabella Lee", "age": 29, "weight": "136 lbs", "height": "5'5\"", "disease": "Interstitial Cystitis", "health_info": "Chronic bladder pain, frequent urination, takes pain management"},
            {"name": "Ethan Davis", "age": 44, "weight": "200 lbs", "height": "6'2\"", "disease": "Obstructive Sleep Apnea", "health_info": "Breathing interruptions during sleep, uses CPAP, daytime sleepiness"},
            {"name": "Charlotte King", "age": 25, "weight": "122 lbs", "height": "5'2\"", "disease": "Postural Orthostatic Tachycardia Syndrome", "health_info": "Heart rate increases with position changes, takes beta blockers, dizziness"},
            {"name": "Mason Young", "age": 37, "weight": "174 lbs", "height": "5'9\"", "disease": "Chronic Pancreatitis", "health_info": "Pancreatic inflammation, pain, takes digestive enzymes"},
            {"name": "Mia Evans", "age": 31, "weight": "144 lbs", "height": "5'5\"", "disease": "Lichen Planus", "health_info": "Inflammatory skin condition, purple papules, requires topical steroids"},
            {"name": "Logan Scott", "age": 39, "weight": "183 lbs", "height": "5'10\"", "disease": "Bursitis", "health_info": "Joint inflammation, shoulder pain, takes NSAIDs and physical therapy"},
            {"name": "Harper Adams", "age": 26, "weight": "127 lbs", "height": "5'3\"", "disease": "Dysthymia", "health_info": "Persistent depressive disorder, takes antidepressants long-term"},
            {"name": "Aiden Robinson", "age": 42, "weight": "195 lbs", "height": "6'1\"", "disease": "Diabetic Neuropathy", "health_info": "Nerve damage from diabetes, foot pain and numbness, requires monitoring"},
            {"name": "Sophie Moore", "age": 28, "weight": "132 lbs", "height": "5'4\"", "disease": "Recurrent Urinary Tract Infections", "health_info": "Multiple UTI episodes yearly, takes prophylactic antibiotics"},
            {"name": "Oliver Murphy", "age": 41, "weight": "189 lbs", "height": "6'0\"", "disease": "Pericarditis", "health_info": "Heart membrane inflammation, chest pain, takes anti-inflammatory medication"},
            {"name": "Emma Clark", "age": 24, "weight": "121 lbs", "height": "5'1\"", "disease": "Hyperthyroidism", "health_info": "Overactive thyroid, takes antithyroid medication, weight loss and tremors"},
            {"name": "Lucas Garcia", "age": 43, "weight": "203 lbs", "height": "6'3\"", "disease": "Hemophilia", "health_info": "Blood clotting disorder, requires factor replacement therapy, bruising easily"},
            {"name": "Ava Phillips", "age": 30, "weight": "139 lbs", "height": "5'5\"", "disease": "Amenorrhea", "health_info": "Absent menstrual periods, hormonal imbalance, requires medical investigation"},
            {"name": "Noah Harris", "age": 38, "weight": "177 lbs", "height": "5'10\"", "disease": "Achilles Tendinitis", "health_info": "Tendon inflammation, ankle pain, requires rest and physical therapy"},
            {"name": "Emmanuelle Mimieux", "age": 16, "weight": "129 lbs", "height": "5'4\"", "disease": "Cyclic Vomiting Syndrome", "health_info": "Recurrent vomiting episodes, takes preventative medication"},
            {"name": "Liam Taylor", "age": 40, "weight": "191 lbs", "height": "6'1\"", "disease": "Spondylitis", "health_info": "Spinal inflammation and stiffness, takes TNF inhibitors"},
            {"name": "Isabella Carter", "age": 29, "weight": "137 lbs", "height": "5'5\"", "disease": "Metatarsalgia", "health_info": "Ball of foot pain, wears specialized footwear, takes pain medication"},
            {"name": "Mason Ross", "age": 44, "weight": "198 lbs", "height": "6'1\"", "disease": "Hyperparathyroidism", "health_info": "Calcium imbalance, bone pain, requires surgical intervention"},
            {"name": "Mia Allen", "age": 26, "weight": "125 lbs", "height": "5'3\"", "disease": "Henoch-Schönlein Purpura", "health_info": "Vasculitis disorder, rash and joint pain, takes immunosuppressants"},
            {"name": "Oliver Jackson", "age": 42, "weight": "193 lbs", "height": "6'1\"", "disease": "Myocardial Infarction History", "health_info": "Previous heart attack, takes multiple cardiac medications, cardiac rehabilitation"},
            {"name": "Sophie King", "age": 31, "weight": "146 lbs", "height": "5'6\"", "disease": "Hyperemesis Gravidarum", "health_info": "Severe pregnancy nausea, requires medication and IV hydration"},
            {"name": "Ethan Brown", "age": 37, "weight": "180 lbs", "height": "5'10\"", "disease": "Spontaneous Pneumothorax", "health_info": "Lung collapse history, requires monitoring for recurrence"},
            {"name": "Harper Wilson", "age": 25, "weight": "123 lbs", "height": "5'2\"", "disease": "Premature Ovarian Failure", "health_info": "Early menopause, takes hormone replacement therapy"},
            {"name": "Logan Mitchell", "age": 39, "weight": "184 lbs", "height": "5'11\"", "disease": "Tinnitus", "health_info": "Ringing in ears, hearing aids fitted, takes sound therapy"},
            {"name": "Ava Davis", "age": 28, "weight": "134 lbs", "height": "5'4\"", "disease": "Temporomandibular Joint Disorder", "health_info": "Jaw pain and clicking, wears bite guard, takes muscle relaxants"},
            {"name": "Lucas Evans", "age": 41, "weight": "196 lbs", "height": "6'1\"", "disease": "Mastoiditis", "health_info": "Ear bone infection history, takes antibiotics, hearing affected"},
            {"name": "Emma Robinson", "age": 30, "weight": "141 lbs", "height": "5'5\"", "disease": "Steatorrhea", "health_info": "Fatty stools from malabsorption, requires pancreatic enzyme therapy"},
            {"name": "Oliver Scott", "age": 36, "weight": "176 lbs", "height": "5'10\"", "disease": "Reactive Arthritis", "health_info": "Post-infection joint inflammation, takes NSAIDs and immunosuppressants"}
        ]
    }
}

def get_files_data():
    """Returns the complete files data"""
    return files_data
